### ISSUE TITLE
Erro ao receber a primeira letra do usuário nas notificações

### ISSUE THREAD

**Issue by AdrianMichael5** [biacosta7/agras#61]
Comportamento Esperado:
Quando um usuário solicita a entrada em uma comunidade sua foto nas notificações do administrador deveria estar com a letra do próprio nome.

Comportamento Atual:
Quando um usuário solicita a entrada em uma comunidade sua foto nas notificações do administrador esta com a letra inicial do próprio administrador.

Passos para Reproduzir:
Um usuário solicita a entrada em uma comunidade.
Administrador clica no ícone de notificação.

Resultado Esperado:
A imagem com a "foto" do usuario deve aparecer com a inicial do mesmo.

Imagem:
![image](https://github.com/user-attachments/assets/51a98e2f-1c7c-4682-8528-58881b00f6f8)

Ambiente:
Navegador: Google Chrome
Sistema Operacional: Windows 11

**Comment by vinivent** [comment]
![image](https://github.com/user-attachments/assets/53603c78-4e8f-4c26-8de2-c21f9ade5440)

done
