### ISSUE TITLE
Corrigir exibição da animação animate-ping na barra de navegação móvel

### ISSUE THREAD

**Issue by AdrianMichael5** [biacosta7/agras#62]
**Descrição**
A animação `animate-ping` do Tailwind está sendo exibida no elemento de notificação da barra de navegação móvel, mesmo quando não há notificações disponíveis. O comportamento esperado é que a animação apareça **somente** quando houver ao menos uma notificação.

**Passos para reproduzir:**
1. Acesse a aplicação no modo mobile.
2. Observe o ícone de notificações na barra de navegação.
3. Mesmo com 0 notificações, a animação `animate-ping` é exibida.

**Comportamento esperado:**  
A animação `animate-ping` deve aparecer apenas quando o número de notificações for maior que 0.

**Possível solução:**  
- Verificar a lógica de exibição da animação no componente da barra de navegação móvel.
- Certificar-se de que o elemento com a classe `animate-ping` seja exibido condicionalmente com base no número de notificações.

**Imagem**
![image](https://github.com/user-attachments/assets/07f2d54b-7b0f-4851-960d-b1bcf6949919)

**Ambiente**
Sistema Operacional: [Windows 10]
Versão do Django: [5.1.1]
Versão do Python: [3.12.6]

**Prioridade**
Alta

**Comment by vinivent** [comment]
done
